-- AlterTable
ALTER TABLE "User" ADD COLUMN     "emailVerified" BOOLEAN,
ADD COLUMN     "name" TEXT,
ALTER COLUMN "firstName" DROP NOT NULL,
ALTER COLUMN "lastName" DROP NOT NULL,
ALTER COLUMN "phoneNumber" DROP NOT NULL;
